name: Image pdf generation

on:
  workflow_dispatch:

env:
  IMAGE_URL: ghcr.io/vaggeliskls/text-to-pdf

jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    name: generate pdf
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{env.IMAGE_URL}}:latest
          platforms: linux/amd64,linux/arm64
          sbom: true
          provenance: true
